site_name: Hack N Code
site_url: https://https://sebastiensauvage.github.io/
theme:
  name: material

  font: false

  language: fr
  
  icon:
    repo: fontawesome/brands/git-alt

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: brown
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    # Pour afficher une barre de navigation
    - navigation.tabs
    # Pour que la barre soit toujours apprente durant un crolling vertical
    - navigation.tabs.sticky
    # Afficher le chemin de la page active sous la barre de navigation
    - navigation.path
    # Bulle info pour revenir en haut de la page lors d'un scroll vers le haut
    - navigation.top
    # ?
#    - navigation.instant
    # Cache l'entête automatiquement avec les scroll descendant
#    - header.autohide

    # Concerne la "Table Of Content"
    - toc.follow
    # Pour intégrer la table des matière à la navigation à gauche
    - toc.integrate
    
    # Ajout d'un pieds de page pour la navigation
#    - navigation.footer
  
extra:
  social:
    # Mastodonte
#    - icon: fontawesome/brands/mastodon 
#      link: https://fosstodon.org/@squidfunk
    # Twitter
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/gricoo59
    # Github
    - icon: fontawesome/brands/github 
      link: https://github.com/SebastienSauvage/SebastienSauvage.github.io
    # Facebook
#    - icon: fontawesome/brands/facebook 
#      link: https://fosstodon.org/@squidfunk
    # Instagram
#    - icon: fontawesome/brands/instagram 
#      link: https://fosstodon.org/@squidfunk
    # Linkedin
#    - icon: fontawesome/brands/linkedin 
#      link: https://fosstodon.org/@squidfunk

copyright: Licence CC-BY-SA - Sébastien SAUVAGE

# Définir le lien vers le git source
repo_url: https://github.com/SebastienSauvage/SebastienSauvage.github.io
# Nom du git source
repo_name: SebastienSauvage/SebastienSauvage.github.io


markdown_extensions:
  - meta
  - abbr
  - admonition
  - def_list
  - attr_list
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tasklist:
      custom_checkbox: false
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: ⚓︎
      toc_depth: 3

#plugins:
#  - search
#  - macros

# Date des dernières mise-à-jour

#  - git-revision-date-localized:
      # Autoriser l'affichage de la date de la dernière mise-à-jour
#  - enable_creation_date: true
      # Format de la date : date, datetime, iso_date, iso_datetime, timeago
#      type: date

#nav:
#  - Accueil:
#    - index.md
#  - Liens:
#    - liens/liens.md
#  - Archives:
#    - archives/
#    - page1 : archives/Cours de 2nde SNT

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
